-- 코드를 입력하세요
# 아이스크림 가게의 상반기 주문 정보 - FIRST_HALF
# SHIPMENT_ID, FLAVOR(PK), TOTAL_ORDER

# 아이스크림 성분에 대한 정보 - ICECREAM_INFO
# FLAVOR, INGREDITENT_TYPE

# 상반기 아이스크림 총주문량이 3,000보다 높으면서
# 아이스크림의 주 성분이 과일인 아이스크림의 맛을
# 총주문량이 큰 순서대로 조회
SELECT FLAVOR
FROM ICECREAM_INFO
WHERE INGREDIENT_TYPE = 'fruit_based'
AND FLAVOR IN (
    SELECT FLAVOR
    FROM FIRST_HALF
    WHERE TOTAL_ORDER >= 3000
    ORDER BY TOTAL_ORDER
)
###
SELECT i.FLAVOR
FROM ICECREAM_INFO i
JOIN FIRST_HALF f
    ON i.FLAVOR = f.FLAVOR
WHERE i.INGREDIENT_TYPE = 'fruit_based'
    AND f.TOTAL_ORDER >= 3000
ORDER BY TOTAL_ORDER DESC;
