-- 코드를 입력하세요
# 중고거래 게시판 정보 - USED_GOODS_BOARD
# BOARD_ID, WRITER_ID, TITLE, CONTENTS, PRICE, CREATED_DATE, STATUS, VIEWS

# 중고거래 게시판 첨부파일 정보 - USED_GOODS_REPLY
# REPLY_ID, BOARD_ID, WRITER_ID, CONTENTS, CREATED_DATE

# 2022년 10월에 작성된 게시글 제목, 게시글 ID, 댓글 ID, 댓글 작성자 ID, 댓글 내용, 댓글 작성일을 조회

SELECT b.TITLE, b.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, DATE_FORMAT(r.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD b
JOIN USED_GOODS_REPLY r
    ON b.BOARD_ID = r.BOARD_ID
WHERE b.CREATED_DATE >= '2022-10-01' 
    AND b.CREATED_DATE < '2022-11-01'
ORDER BY r.CREATED_DATE, b.TITLE;