-- 코드를 입력하세요
-- 경제 카테고리 속하는 도서
-- 출판일 기준 오름차순
SELECT b.BOOK_ID, a.AUTHOR_NAME, DATE_FORMAT(b.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK b
LEFT JOIN AUTHOR a ON a.AUTHOR_ID = b.AUTHOR_ID
WHERE b.CATEGORY like '경제'
ORDER BY b.PUBLISHED_DATE ASC;
